services:
  - type: web
    name: islamtimeworldbot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false

      - key: WEBAPP_URL
        value: "https://islamtimeworld.com/app"

      - key: WEBHOOK_BASE
        value: "https://islamtimeworldbot-dbup.onrender.com"

      - key: PYTHONIOENCODING
        value: "utf-8"

      - key: ADMIN_IDS
        sync: false