(function () {
  'use strict';

  var LANGS = [
    ['uz', "O'zbek", 'UZ', 'uz.svg', 'ltr'], ['en', 'English', 'EN', 'gb.svg', 'ltr'],
    ['ru', 'Русский', 'RU', 'ru.svg', 'ltr'], ['tr', 'Türkçe', 'TR', 'tr.svg', 'ltr'],
    ['ar', 'العربية', 'AR', 'sa.svg', 'rtl'], ['de', 'Deutsch', 'DE', 'de.svg', 'ltr'],
    ['fr', 'Français', 'FR', 'fr.svg', 'ltr'], ['id', 'Indonesia', 'ID', 'id.svg', 'ltr'],
    ['hi', 'हिन्दी', 'HI', 'in.svg', 'ltr'], ['ur', 'اردو', 'UR', 'pk.svg', 'rtl'],
    ['bn', 'বাংলা', 'BN', 'bd.svg', 'ltr'], ['fa', 'فارسی', 'FA', 'ir.svg', 'rtl'],
    ['ms', 'Melayu', 'MS', 'my.svg', 'ltr']
  ];

  var P = {
    uz: {home:'Bosh sahifa',features:'Imkoniyatlar',about:'Ilova haqida',trust:'Ishonchli asos',help:'Yordam',openBot:'Telegram botni ochish',pill:'Bir umma · Bir ilova · Yaxshiroq kelajak',hero:'Har bir musulmon uchun ishonchli hamrohlik',sub:"Namoz vaqtlari, Qur'on, Qibla, Hadis, Duolar, Hijriy taqvim va yana ko‘p imkoniyatlar — barchasi bitta ilovada.",langs:'15 ta til',schools:'4 mazhab',sources:'Ishonchli manbalar',caption:"Ilova ekranlari namuna ma'lumotlar bilan ko‘rsatilgan.",sourceDesc:"Manbasi ko‘rsatilgan diniy mazmun",world:'Dunyo musulmonlari uchun',schoolDesc:"Hanafiy, Shofi'iy, Molikiy, Hanbaliy",updates:'Doimiy yangilanish',quality:'Sifat va ishonchlilik',featureHead:'Asosiy imkoniyatlar',featureSub:"Sizga kerak bo‘lgan barcha islomiy imkoniyatlar — bitta ilovada",featureInfo:"Batafsil ma’lumot va barcha imkoniyatlar ilovada mavjud.",liveShort:'Makkah va Madinahning rasmiy 24/7 jonli efiri.',liveTitle:'Makkah va Madinah — har doim siz bilan',liveText:'Masjid al-Haram va Masjid an-Nabaviy jonli efirini Saudiya rasmiy kanallarida tomosha qiling.',makkah:'Makkah jonli efiri',madinah:'Madina jonli efiri',oneApp:'Bitta ilova — butun dunyo musulmonlari uchun',allMuslims:'Barcha musulmonlar uchun qulay',useToday:"Bugunoq IslamTimeWorld'dan foydalaning",useSub:"Hozir Telegram bot orqali foydalaning va rasmiy Haramayn efirlarini tomosha qiling.",privacy:'Maxfiylik siyosati',terms:'Foydalanish shartlari',contact:"Biz bilan bog‘lanish",rights:'Barcha huquqlar himoyalangan.',photos:'Fotosuratlar: Wikimedia Commons (CC0).',founder:'Asoschisi',scan:'Telegram botni telefoningizda ochish uchun QR-kodni skanerlang',active:'faol',choose:'Tilni tanlash',menuOpen:'Menyuni ochish',menuClose:'Menyuni yopish'},
    en: {home:'Home',features:'Features',about:'About the app',trust:'Trusted foundation',help:'Help',openBot:'Open Telegram bot',pill:'One Ummah · One app · A better future',hero:'A trusted companion for every Muslim',sub:'Prayer times, Quran, Qibla, Hadith, Duas, Hijri calendar and more — all in one app.',langs:'15 languages',schools:'4 madhhabs',sources:'Trusted sources',caption:'App screens are shown with sample data.',sourceDesc:'Religious content with cited sources',world:'For Muslims worldwide',schoolDesc:"Hanafi, Shafi'i, Maliki, Hanbali",updates:'Continuous updates',quality:'Quality and reliability',featureHead:'Core features',featureSub:'The Islamic tools you need — in one app',featureInfo:'Full details and functionality are available in the app.',liveShort:'Official 24/7 live broadcasts from Makkah and Madinah.',liveTitle:'Makkah and Madinah — always with you',liveText:'Watch Masjid al-Haram and Masjid an-Nabawi live on the official Saudi channels.',makkah:'Watch Makkah live',madinah:'Watch Madinah live',oneApp:'One app — for Muslims worldwide',allMuslims:'Made for all Muslims',useToday:'Use IslamTimeWorld today',useSub:'Use the Telegram bot now and watch the official Haramayn broadcasts.',privacy:'Privacy policy',terms:'Terms of use',contact:'Contact us',rights:'All rights reserved.',photos:'Photos: Wikimedia Commons (CC0).',founder:'Founder',scan:'Scan the QR code to open the Telegram bot on your phone',active:'active',choose:'Choose language',menuOpen:'Open menu',menuClose:'Close menu'},
    ru: {home:'Главная',features:'Возможности',about:'О приложении',trust:'Надёжная основа',help:'Помощь',openBot:'Открыть Telegram-бот',pill:'Одна умма · Одно приложение · Лучшее будущее',hero:'Надёжный помощник для каждого мусульманина',sub:'Время намаза, Коран, Кибла, хадисы, дуа, календарь хиджры и многое другое — в одном приложении.',langs:'15 языков',schools:'4 мазхаба',sources:'Надёжные источники',caption:'Экраны приложения показаны с примерными данными.',sourceDesc:'Религиозные материалы с указанием источников',world:'Для мусульман всего мира',schoolDesc:'Ханафи, Шафии, Малики, Ханбали',updates:'Постоянные обновления',quality:'Качество и надёжность',featureHead:'Основные возможности',featureSub:'Все необходимые исламские функции — в одном приложении',featureInfo:'Подробности и все функции доступны в приложении.',liveShort:'Официальные круглосуточные эфиры из Мекки и Медины.',liveTitle:'Мекка и Медина — всегда рядом',liveText:'Смотрите прямые эфиры Масджид аль-Харам и Масджид ан-Набави на официальных саудовских каналах.',makkah:'Мекка — прямой эфир',madinah:'Медина — прямой эфир',oneApp:'Одно приложение — для мусульман всего мира',allMuslims:'Удобно для всех мусульман',useToday:'Начните пользоваться IslamTimeWorld сегодня',useSub:'Откройте Telegram-бот и смотрите официальные эфиры Харамайна.',privacy:'Политика конфиденциальности',terms:'Условия использования',contact:'Связаться с нами',rights:'Все права защищены.',photos:'Фото: Wikimedia Commons (CC0).',founder:'Основатель',scan:'Отсканируйте QR-код, чтобы открыть Telegram-бот',active:'активен',choose:'Выбрать язык',menuOpen:'Открыть меню',menuClose:'Закрыть меню'},
    tr: {home:'Ana sayfa',features:'Özellikler',about:'Uygulama hakkında',trust:'Güvenilir temel',help:'Yardım',openBot:"Telegram botunu aç",pill:'Tek ümmet · Tek uygulama · Daha iyi gelecek',hero:'Her Müslüman için güvenilir bir yol arkadaşı',sub:"Namaz vakitleri, Kur'an, Kıble, Hadis, Dualar, Hicri takvim ve daha fazlası — tek uygulamada.",langs:'15 dil',schools:'4 mezhep',sources:'Güvenilir kaynaklar',caption:'Uygulama ekranları örnek verilerle gösterilir.',sourceDesc:'Kaynakları belirtilmiş dini içerik',world:'Dünya Müslümanları için',schoolDesc:'Hanefi, Şafii, Maliki, Hanbeli',updates:'Sürekli güncelleme',quality:'Kalite ve güvenilirlik',featureHead:'Temel özellikler',featureSub:'İhtiyacınız olan İslami araçlar — tek uygulamada',featureInfo:'Ayrıntılar ve tüm özellikler uygulamada mevcuttur.',liveShort:'Mekke ve Medine’den resmi 7/24 canlı yayın.',liveTitle:'Mekke ve Medine — her zaman yanınızda',liveText:"Mescid-i Haram ve Mescid-i Nebevi'yi resmi Suudi kanallarından canlı izleyin.",makkah:'Mekke canlı yayın',madinah:'Medine canlı yayın',oneApp:'Tek uygulama — tüm dünya Müslümanları için',allMuslims:'Tüm Müslümanlar için uygun',useToday:"IslamTimeWorld'ü bugün kullanın",useSub:'Telegram botunu kullanın ve resmi Haremeyn yayınlarını izleyin.',privacy:'Gizlilik politikası',terms:'Kullanım koşulları',contact:'Bize ulaşın',rights:'Tüm hakları saklıdır.',photos:'Fotoğraflar: Wikimedia Commons (CC0).',founder:'Kurucu',scan:'Telegram botunu açmak için QR kodunu tarayın',active:'aktif',choose:'Dil seçin',menuOpen:'Menüyü aç',menuClose:'Menüyü kapat'},
    ar: {home:'الرئيسية',features:'المميزات',about:'عن التطبيق',trust:'مصادر موثوقة',help:'المساعدة',openBot:'فتح بوت تيليجرام',pill:'أمة واحدة · تطبيق واحد · مستقبل أفضل',hero:'رفيق موثوق لكل مسلم',sub:'مواقيت الصلاة والقرآن والقبلة والحديث والأدعية والتقويم الهجري والمزيد — في تطبيق واحد.',langs:'15 لغة',schools:'4 مذاهب',sources:'مصادر موثوقة',caption:'تُعرض شاشات التطبيق ببيانات تجريبية.',sourceDesc:'محتوى ديني موثق المصادر',world:'للمسلمين حول العالم',schoolDesc:'الحنفي، الشافعي، المالكي، الحنبلي',updates:'تحديثات مستمرة',quality:'الجودة والموثوقية',featureHead:'المميزات الأساسية',featureSub:'كل الأدوات الإسلامية التي تحتاجها في تطبيق واحد',featureInfo:'التفاصيل وجميع الوظائف متاحة داخل التطبيق.',liveShort:'بث رسمي مباشر على مدار الساعة من مكة والمدينة.',liveTitle:'مكة والمدينة — معك دائماً',liveText:'شاهد المسجد الحرام والمسجد النبوي مباشرة عبر القنوات السعودية الرسمية.',makkah:'مشاهدة مكة مباشرة',madinah:'مشاهدة المدينة مباشرة',oneApp:'تطبيق واحد للمسلمين حول العالم',allMuslims:'مناسب لجميع المسلمين',useToday:'استخدم IslamTimeWorld اليوم',useSub:'استخدم بوت تيليجرام وشاهد البث الرسمي للحرمين.',privacy:'سياسة الخصوصية',terms:'شروط الاستخدام',contact:'اتصل بنا',rights:'جميع الحقوق محفوظة.',photos:'الصور: ويكيميديا كومنز (CC0).',founder:'المؤسس',scan:'امسح رمز QR لفتح بوت تيليجرام',active:'نشط',choose:'اختر اللغة',menuOpen:'فتح القائمة',menuClose:'إغلاق القائمة'},
    de: {home:'Startseite',features:'Funktionen',about:'Über die App',trust:'Vertrauensbasis',help:'Hilfe',openBot:'Telegram-Bot öffnen',pill:'Eine Umma · Eine App · Eine bessere Zukunft',hero:'Ein verlässlicher Begleiter für jeden Muslim',sub:'Gebetszeiten, Koran, Qibla, Hadithe, Duas, Hidschri-Kalender und mehr — alles in einer App.',langs:'15 Sprachen',schools:'4 Rechtsschulen',sources:'Vertrauenswürdige Quellen',caption:'App-Bildschirme werden mit Beispieldaten gezeigt.',sourceDesc:'Religiöse Inhalte mit Quellenangaben',world:'Für Muslime weltweit',schoolDesc:"Hanafi, Schafi'i, Maliki, Hanbali",updates:'Laufende Aktualisierungen',quality:'Qualität und Zuverlässigkeit',featureHead:'Hauptfunktionen',featureSub:'Die islamischen Werkzeuge, die Sie brauchen — in einer App',featureInfo:'Details und alle Funktionen sind in der App verfügbar.',liveShort:'Offizielle 24/7-Livestreams aus Mekka und Medina.',liveTitle:'Mekka und Medina — immer bei Ihnen',liveText:'Sehen Sie Masjid al-Haram und Masjid an-Nabawi live auf den offiziellen saudischen Kanälen.',makkah:'Mekka live ansehen',madinah:'Medina live ansehen',oneApp:'Eine App — für Muslime weltweit',allMuslims:'Für alle Muslime geeignet',useToday:'IslamTimeWorld heute nutzen',useSub:'Nutzen Sie den Telegram-Bot und sehen Sie die offiziellen Haramayn-Streams.',privacy:'Datenschutz',terms:'Nutzungsbedingungen',contact:'Kontakt',rights:'Alle Rechte vorbehalten.',photos:'Fotos: Wikimedia Commons (CC0).',founder:'Gründer',scan:'QR-Code scannen, um den Telegram-Bot zu öffnen',active:'aktiv',choose:'Sprache wählen',menuOpen:'Menü öffnen',menuClose:'Menü schließen'},
    fr: {home:'Accueil',features:'Fonctionnalités',about:"À propos de l'app",trust:'Base fiable',help:'Aide',openBot:'Ouvrir le bot Telegram',pill:'Une Oumma · Une application · Un avenir meilleur',hero:'Un compagnon fiable pour chaque musulman',sub:'Horaires de prière, Coran, Qibla, Hadiths, invocations, calendrier hégirien et plus — dans une seule application.',langs:'15 langues',schools:'4 écoles',sources:'Sources fiables',caption:"Écrans de l'application présentés avec des données d'exemple.",sourceDesc:'Contenu religieux avec sources citées',world:'Pour les musulmans du monde entier',schoolDesc:'Hanafite, Chaféite, Malikite, Hanbalite',updates:'Mises à jour continues',quality:'Qualité et fiabilité',featureHead:'Fonctionnalités principales',featureSub:'Les outils islamiques dont vous avez besoin — dans une seule application',featureInfo:"Les détails et toutes les fonctions sont disponibles dans l'application.",liveShort:'Diffusions officielles 24h/24 depuis La Mecque et Médine.',liveTitle:'La Mecque et Médine — toujours avec vous',liveText:'Regardez Masjid al-Haram et Masjid an-Nabawi en direct sur les chaînes saoudiennes officielles.',makkah:'Voir La Mecque en direct',madinah:'Voir Médine en direct',oneApp:'Une application — pour les musulmans du monde entier',allMuslims:'Adaptée à tous les musulmans',useToday:"Utilisez IslamTimeWorld dès aujourd'hui",useSub:'Utilisez le bot Telegram et regardez les diffusions officielles des Haramayn.',privacy:'Politique de confidentialité',terms:"Conditions d'utilisation",contact:'Nous contacter',rights:'Tous droits réservés.',photos:'Photos : Wikimedia Commons (CC0).',founder:'Fondateur',scan:'Scannez le QR code pour ouvrir le bot Telegram',active:'actif',choose:'Choisir la langue',menuOpen:'Ouvrir le menu',menuClose:'Fermer le menu'},
    id: {home:'Beranda',features:'Fitur',about:'Tentang aplikasi',trust:'Dasar tepercaya',help:'Bantuan',openBot:'Buka bot Telegram',pill:'Satu umat · Satu aplikasi · Masa depan lebih baik',hero:'Pendamping tepercaya bagi setiap Muslim',sub:'Waktu salat, Al-Quran, Kiblat, Hadis, Doa, kalender Hijriah, dan lainnya — semua dalam satu aplikasi.',langs:'15 bahasa',schools:'4 mazhab',sources:'Sumber tepercaya',caption:'Layar aplikasi ditampilkan dengan data contoh.',sourceDesc:'Konten agama dengan sumber yang jelas',world:'Untuk Muslim di seluruh dunia',schoolDesc:"Hanafi, Syafi'i, Maliki, Hanbali",updates:'Pembaruan berkelanjutan',quality:'Kualitas dan keandalan',featureHead:'Fitur utama',featureSub:'Semua alat Islami yang Anda perlukan — dalam satu aplikasi',featureInfo:'Rincian dan semua fitur tersedia di aplikasi.',liveShort:'Siaran resmi 24/7 dari Makkah dan Madinah.',liveTitle:'Makkah dan Madinah — selalu bersama Anda',liveText:'Saksikan Masjid al-Haram dan Masjid an-Nabawi secara langsung di kanal resmi Saudi.',makkah:'Tonton Makkah LIVE',madinah:'Tonton Madinah LIVE',oneApp:'Satu aplikasi — untuk Muslim di seluruh dunia',allMuslims:'Nyaman untuk semua Muslim',useToday:'Gunakan IslamTimeWorld hari ini',useSub:'Gunakan bot Telegram dan saksikan siaran resmi Haramayn.',privacy:'Kebijakan privasi',terms:'Ketentuan penggunaan',contact:'Hubungi kami',rights:'Hak cipta dilindungi.',photos:'Foto: Wikimedia Commons (CC0).',founder:'Pendiri',scan:'Pindai kode QR untuk membuka bot Telegram',active:'aktif',choose:'Pilih bahasa',menuOpen:'Buka menu',menuClose:'Tutup menu'},
    hi: {home:'मुखपृष्ठ',features:'सुविधाएँ',about:'ऐप के बारे में',trust:'विश्वसनीय आधार',help:'सहायता',openBot:'Telegram बॉट खोलें',pill:'एक उम्मत · एक ऐप · बेहतर भविष्य',hero:'हर मुसलमान के लिए विश्वसनीय साथी',sub:'नमाज़ का समय, क़ुरआन, क़िबला, हदीस, दुआएँ, हिजरी कैलेंडर और बहुत कुछ — एक ही ऐप में।',langs:'15 भाषाएँ',schools:'4 मज़हब',sources:'विश्वसनीय स्रोत',caption:'ऐप स्क्रीन नमूना डेटा के साथ दिखाई गई हैं।',sourceDesc:'स्रोत सहित धार्मिक सामग्री',world:'दुनिया भर के मुसलमानों के लिए',schoolDesc:'हनफ़ी, शाफ़ई, मालिकी, हनबली',updates:'निरंतर अपडेट',quality:'गुणवत्ता और विश्वसनीयता',featureHead:'मुख्य सुविधाएँ',featureSub:'आपके लिए आवश्यक इस्लामी साधन — एक ऐप में',featureInfo:'विवरण और सभी सुविधाएँ ऐप में उपलब्ध हैं।',liveShort:'मक्का और मदीना से आधिकारिक 24/7 लाइव प्रसारण।',liveTitle:'मक्का और मदीना — हमेशा आपके साथ',liveText:'मस्जिद अल-हरम और मस्जिद अन-नबवी को आधिकारिक सऊदी चैनलों पर लाइव देखें।',makkah:'मक्का लाइव देखें',madinah:'मदीना लाइव देखें',oneApp:'एक ऐप — दुनिया भर के मुसलमानों के लिए',allMuslims:'सभी मुसलमानों के लिए सुविधाजनक',useToday:'आज ही IslamTimeWorld का उपयोग करें',useSub:'Telegram बॉट उपयोग करें और आधिकारिक हरमैन प्रसारण देखें।',privacy:'गोपनीयता नीति',terms:'उपयोग की शर्तें',contact:'संपर्क करें',rights:'सर्वाधिकार सुरक्षित।',photos:'फ़ोटो: Wikimedia Commons (CC0)।',founder:'संस्थापक',scan:'Telegram बॉट खोलने के लिए QR कोड स्कैन करें',active:'सक्रिय',choose:'भाषा चुनें',menuOpen:'मेनू खोलें',menuClose:'मेनू बंद करें'},
    ur: {home:'صفحۂ اول',features:'خصوصیات',about:'ایپ کے بارے میں',trust:'قابل اعتماد بنیاد',help:'مدد',openBot:'ٹیلیگرام بوٹ کھولیں',pill:'ایک امت · ایک ایپ · بہتر مستقبل',hero:'ہر مسلمان کے لیے قابل اعتماد ساتھی',sub:'نماز کے اوقات، قرآن، قبلہ، حدیث، دعائیں، ہجری کیلنڈر اور بہت کچھ — ایک ہی ایپ میں۔',langs:'15 زبانیں',schools:'4 مذاہب',sources:'قابل اعتماد ذرائع',caption:'ایپ اسکرینیں نمونہ ڈیٹا کے ساتھ دکھائی گئی ہیں۔',sourceDesc:'حوالہ شدہ دینی مواد',world:'دنیا بھر کے مسلمانوں کے لیے',schoolDesc:'حنفی، شافعی، مالکی، حنبلی',updates:'مسلسل اپ ڈیٹس',quality:'معیار اور اعتماد',featureHead:'اہم خصوصیات',featureSub:'ضروری اسلامی سہولیات — ایک ایپ میں',featureInfo:'تفصیل اور تمام سہولیات ایپ میں موجود ہیں۔',liveShort:'مکہ اور مدینہ سے سرکاری 24/7 براہ راست نشریات۔',liveTitle:'مکہ اور مدینہ — ہمیشہ آپ کے ساتھ',liveText:'مسجد الحرام اور مسجد نبوی کی براہ راست نشریات سرکاری سعودی چینلز پر دیکھیں۔',makkah:'مکہ براہ راست دیکھیں',madinah:'مدینہ براہ راست دیکھیں',oneApp:'ایک ایپ — دنیا بھر کے مسلمانوں کے لیے',allMuslims:'تمام مسلمانوں کے لیے موزوں',useToday:'آج ہی IslamTimeWorld استعمال کریں',useSub:'ٹیلیگرام بوٹ استعمال کریں اور حرمین کی سرکاری نشریات دیکھیں۔',privacy:'رازداری کی پالیسی',terms:'استعمال کی شرائط',contact:'ہم سے رابطہ کریں',rights:'جملہ حقوق محفوظ ہیں۔',photos:'تصاویر: Wikimedia Commons (CC0)۔',founder:'بانی',scan:'ٹیلیگرام بوٹ کھولنے کے لیے QR کوڈ اسکین کریں',active:'فعال',choose:'زبان منتخب کریں',menuOpen:'مینو کھولیں',menuClose:'مینو بند کریں'},
    bn: {home:'হোম',features:'সুবিধাসমূহ',about:'অ্যাপ সম্পর্কে',trust:'বিশ্বস্ত ভিত্তি',help:'সহায়তা',openBot:'Telegram বট খুলুন',pill:'এক উম্মাহ · এক অ্যাপ · উন্নত ভবিষ্যৎ',hero:'প্রত্যেক মুসলিমের বিশ্বস্ত সঙ্গী',sub:'নামাজের সময়, কুরআন, কিবলা, হাদিস, দোয়া, হিজরি ক্যালেন্ডার এবং আরও অনেক কিছু — এক অ্যাপে।',langs:'১৫টি ভাষা',schools:'৪ মাজহাব',sources:'বিশ্বস্ত উৎস',caption:'অ্যাপের স্ক্রিনগুলো নমুনা তথ্যসহ দেখানো হয়েছে।',sourceDesc:'উৎসসহ যাচাইকৃত ধর্মীয় বিষয়বস্তু',world:'বিশ্বের মুসলিমদের জন্য',schoolDesc:'হানাফি, শাফেয়ি, মালিকি, হাম্বলি',updates:'নিয়মিত হালনাগাদ',quality:'মান ও নির্ভরযোগ্যতা',featureHead:'প্রধান সুবিধাসমূহ',featureSub:'আপনার প্রয়োজনীয় ইসলামি সুবিধা — এক অ্যাপে',featureInfo:'বিস্তারিত ও সব সুবিধা অ্যাপে পাওয়া যায়।',liveShort:'মক্কা ও মদিনা থেকে সরকারি ২৪/৭ সরাসরি সম্প্রচার।',liveTitle:'মক্কা ও মদিনা — সবসময় আপনার সঙ্গে',liveText:'সরকারি সৌদি চ্যানেলে মসজিদুল হারাম ও মসজিদে নববীর সরাসরি সম্প্রচার দেখুন।',makkah:'মক্কা লাইভ দেখুন',madinah:'মদিনা লাইভ দেখুন',oneApp:'এক অ্যাপ — বিশ্বজুড়ে মুসলিমদের জন্য',allMuslims:'সব মুসলিমের জন্য সুবিধাজনক',useToday:'আজই IslamTimeWorld ব্যবহার করুন',useSub:'Telegram বট ব্যবহার করুন এবং সরকারি হারামাইন সম্প্রচার দেখুন।',privacy:'গোপনীয়তা নীতি',terms:'ব্যবহারের শর্তাবলি',contact:'যোগাযোগ করুন',rights:'সর্বস্বত্ব সংরক্ষিত।',photos:'ছবি: Wikimedia Commons (CC0)।',founder:'প্রতিষ্ঠাতা',scan:'Telegram বট খুলতে QR কোড স্ক্যান করুন',active:'সক্রিয়',choose:'ভাষা নির্বাচন করুন',menuOpen:'মেনু খুলুন',menuClose:'মেনু বন্ধ করুন'},
    fa: {home:'خانه',features:'امکانات',about:'درباره برنامه',trust:'پایه معتبر',help:'راهنما',openBot:'باز کردن ربات تلگرام',pill:'یک امت · یک برنامه · آینده‌ای بهتر',hero:'همراهی مطمئن برای هر مسلمان',sub:'اوقات نماز، قرآن، قبله، حدیث، دعاها، تقویم هجری و امکانات بیشتر — همه در یک برنامه.',langs:'۱۵ زبان',schools:'۴ مذهب',sources:'منابع معتبر',caption:'صفحه‌های برنامه با داده‌های نمونه نمایش داده شده‌اند.',sourceDesc:'محتوای دینی همراه با ذکر منبع',world:'برای مسلمانان سراسر جهان',schoolDesc:'حنفی، شافعی، مالکی، حنبلی',updates:'به‌روزرسانی مداوم',quality:'کیفیت و اطمینان',featureHead:'امکانات اصلی',featureSub:'ابزارهای اسلامی مورد نیاز شما — در یک برنامه',featureInfo:'جزئیات و همه امکانات در برنامه در دسترس است.',liveShort:'پخش رسمی شبانه‌روزی از مکه و مدینه.',liveTitle:'مکه و مدینه — همیشه همراه شما',liveText:'مسجدالحرام و مسجدالنبی را از کانال‌های رسمی سعودی زنده تماشا کنید.',makkah:'پخش زنده مکه',madinah:'پخش زنده مدینه',oneApp:'یک برنامه — برای مسلمانان سراسر جهان',allMuslims:'مناسب برای همه مسلمانان',useToday:'امروز از IslamTimeWorld استفاده کنید',useSub:'از ربات تلگرام استفاده کنید و پخش رسمی حرمین را ببینید.',privacy:'سیاست حریم خصوصی',terms:'شرایط استفاده',contact:'تماس با ما',rights:'تمام حقوق محفوظ است.',photos:'عکس‌ها: Wikimedia Commons (CC0).',founder:'بنیان‌گذار',scan:'برای باز کردن ربات تلگرام کد QR را اسکن کنید',active:'فعال',choose:'انتخاب زبان',menuOpen:'باز کردن منو',menuClose:'بستن منو'},
    ms: {home:'Laman utama',features:'Ciri-ciri',about:'Tentang aplikasi',trust:'Asas dipercayai',help:'Bantuan',openBot:'Buka bot Telegram',pill:'Satu ummah · Satu aplikasi · Masa depan lebih baik',hero:'Teman dipercayai bagi setiap Muslim',sub:'Waktu solat, al-Quran, Kiblat, Hadis, Doa, kalendar Hijrah dan banyak lagi — semuanya dalam satu aplikasi.',langs:'15 bahasa',schools:'4 mazhab',sources:'Sumber dipercayai',caption:'Skrin aplikasi dipaparkan dengan data contoh.',sourceDesc:'Kandungan agama berserta sumber',world:'Untuk Muslim seluruh dunia',schoolDesc:"Hanafi, Syafi'i, Maliki, Hanbali",updates:'Kemas kini berterusan',quality:'Kualiti dan kebolehpercayaan',featureHead:'Ciri utama',featureSub:'Kemudahan Islam yang anda perlukan — dalam satu aplikasi',featureInfo:'Butiran dan semua fungsi tersedia dalam aplikasi.',liveShort:'Siaran langsung rasmi 24/7 dari Makkah dan Madinah.',liveTitle:'Makkah dan Madinah — sentiasa bersama anda',liveText:'Tonton Masjid al-Haram dan Masjid an-Nabawi secara langsung di saluran rasmi Saudi.',makkah:'Tonton Makkah LIVE',madinah:'Tonton Madinah LIVE',oneApp:'Satu aplikasi — untuk Muslim seluruh dunia',allMuslims:'Sesuai untuk semua Muslim',useToday:'Gunakan IslamTimeWorld hari ini',useSub:'Gunakan bot Telegram dan tonton siaran rasmi Haramayn.',privacy:'Dasar privasi',terms:'Syarat penggunaan',contact:'Hubungi kami',rights:'Hak cipta terpelihara.',photos:'Foto: Wikimedia Commons (CC0).',founder:'Pengasas',scan:'Imbas kod QR untuk membuka bot Telegram',active:'aktif',choose:'Pilih bahasa',menuOpen:'Buka menu',menuClose:'Tutup menu'}
  };

  var FEATURE_TITLES = {
    uz:["Namoz vaqtlari","Qibla","Al-Qur'on","Hadislar","Duolar va zikrlar","Hijriy taqvim","Yaqin masjidlar","Qazo namozlari","Shahodat va Kalimalar","99 ismlar","Haramayn LIVE","Mazhab ma'lumotlari"],
    en:['Prayer times','Qibla','The Quran','Hadiths','Duas and dhikr','Hijri calendar','Nearby mosques','Missed prayers','Shahada and Kalimas','99 Names','Haramayn LIVE','Madhhab guidance'],
    ru:['Время намаза','Кибла','Коран','Хадисы','Дуа и зикры','Календарь хиджры','Ближайшие мечети','Пропущенные намазы','Шахада и калимы','99 имён','Харамайн LIVE','Сведения о мазхабах'],
    tr:['Namaz vakitleri','Kıble',"Kur'an",'Hadisler','Dualar ve zikirler','Hicri takvim','Yakındaki camiler','Kaza namazları','Şehadet ve Kelimeler','99 İsim','Haremeyn LIVE','Mezhep bilgileri'],
    ar:['مواقيت الصلاة','القبلة','القرآن الكريم','الأحاديث','الأدعية والأذكار','التقويم الهجري','المساجد القريبة','الصلوات الفائتة','الشهادة والكلمات','أسماء الله الحسنى','الحرمين مباشر','معلومات المذاهب'],
    de:['Gebetszeiten','Qibla','Der Koran','Hadithe','Duas und Dhikr','Hidschri-Kalender','Moscheen in der Nähe','Nachholgebete','Schahada und Kalimas','99 Namen','Haramayn LIVE','Rechtsschulen'],
    fr:['Horaires de prière','Qibla','Le Coran','Hadiths','Invocations et dhikr','Calendrier hégirien','Mosquées proches','Prières manquées','Shahada et Kalimas','99 Noms','Haramayn LIVE','Écoles juridiques'],
    id:['Waktu salat','Kiblat','Al-Quran','Hadis','Doa dan zikir','Kalender Hijriah','Masjid terdekat','Salat qadha','Syahadat dan Kalimat','99 Nama','Haramayn LIVE','Panduan mazhab'],
    hi:['नमाज़ का समय','क़िबला','क़ुरआन','हदीस','दुआ और ज़िक्र','हिजरी कैलेंडर','नज़दीकी मस्जिदें','क़ज़ा नमाज़','शहादा और कलिमा','99 नाम','हरमैन लाइव','मज़हब मार्गदर्शन'],
    ur:['نماز کے اوقات','قبلہ','قرآن','احادیث','دعائیں اور اذکار','ہجری کیلنڈر','قریبی مساجد','قضا نمازیں','شہادت اور کلمات','99 نام','حرمین لائیو','مذہبی رہنمائی'],
    bn:['নামাজের সময়','কিবলা','কুরআন','হাদিস','দোয়া ও জিকির','হিজরি ক্যালেন্ডার','কাছের মসজিদ','কাজা নামাজ','শাহাদাহ ও কালিমা','৯৯ নাম','হারামাইন লাইভ','মাজহাব নির্দেশিকা'],
    fa:['اوقات نماز','قبله','قرآن','احادیث','دعاها و ذکرها','تقویم هجری','مساجد نزدیک','نمازهای قضا','شهادت و کلمات','۹۹ نام','پخش زنده حرمین','راهنمای مذاهب'],
    ms:['Waktu solat','Kiblat','Al-Quran','Hadis','Doa dan zikir','Kalendar Hijrah','Masjid berdekatan','Solat qada','Syahadah dan Kalimah','99 Nama','Haramayn LIVE','Panduan mazhab']
  };
  var SLOGANS = {uz:"Har kuningiz Allohga yaqinroq bo‘lsin!",en:'May every day bring you closer to Allah!',ru:'Пусть каждый день приближает вас к Аллаху!',tr:"Her gününüz sizi Allah'a daha da yaklaştırsın!",ar:'فليقرّبك كل يوم من الله!',de:'Möge jeder Tag Sie Allah näherbringen!',fr:"Que chaque jour vous rapproche d'Allah !",id:'Semoga setiap harimu semakin dekat dengan Allah!',hi:'हर दिन आपको अल्लाह के और करीब ले जाए!',ur:'ہر دن آپ کو اللہ کے قریب تر لے جائے!',bn:'প্রতিটি দিন যেন আপনাকে আল্লাহর আরও কাছে নিয়ে যায়!',fa:'باشد که هر روزتان شما را به خدا نزدیک‌تر کند!',ms:'Semoga setiap hari anda semakin dekat dengan Allah!'};
  var SOON = {uz:'Tez orada',en:'Coming soon',ru:'Скоро',tr:'Yakında',ar:'قريباً',de:'Demnächst',fr:'Bientôt',id:'Segera hadir',hi:'जल्द आ रहा है',ur:'جلد آرہا ہے',bn:'শীঘ্রই আসছে',fa:'به‌زودی',ms:'Akan datang'};
  var VIDEO = {uz:'Ilova haqida video',en:'About the app video',ru:'Видео о приложении',tr:'Uygulama videosu',ar:'فيديو عن التطبيق',de:'Video über die App',fr:"Vidéo sur l'application",id:'Video tentang aplikasi',hi:'ऐप के बारे में वीडियो',ur:'ایپ کے بارے میں ویڈیو',bn:'অ্যাপ পরিচিতি ভিডিও',fa:'ویدیوی معرفی برنامه',ms:'Video tentang aplikasi'};
  var SKIP = {uz:"Asosiy mazmunga o‘tish",en:'Skip to main content',ru:'Перейти к основному содержанию',tr:'Ana içeriğe geç',ar:'الانتقال إلى المحتوى الرئيسي',de:'Zum Hauptinhalt springen',fr:'Aller au contenu principal',id:'Lewati ke konten utama',hi:'मुख्य सामग्री पर जाएँ',ur:'مرکزی مواد پر جائیں',bn:'মূল বিষয়বস্তুতে যান',fa:'رفتن به محتوای اصلی',ms:'Langkau ke kandungan utama'};

  function all(selector) { return Array.prototype.slice.call(document.querySelectorAll(selector)); }
  function text(selector, value) { all(selector).forEach(function (el) { el.textContent = value; }); }
  function label(selector, value) { all(selector).forEach(function (el) { var node = Array.prototype.find.call(el.childNodes, function (n) { return n.nodeType === 3 && n.nodeValue.trim(); }); if (node) node.nodeValue = ' ' + value + ' '; else el.appendChild(document.createTextNode(value)); }); }
  function nth(selector, values) { all(selector).forEach(function (el, i) { if (values[i] != null) el.textContent = values[i]; }); }
  function languageMeta(code) { return LANGS.find(function (x) { return x[0] === code; }) || LANGS[0]; }

  function renderMenu(code, p) {
    var menu = document.getElementById('langMenu');
    menu.innerHTML = '';
    LANGS.forEach(function (lang) {
      var button = document.createElement('button');
      button.type = 'button'; button.className = 'lang-item' + (lang[0] === code ? ' is-current' : '');
      button.dataset.lang = lang[0];
      if (lang[0] === code) button.setAttribute('aria-current', 'true');
      button.innerHTML = '<img class="lang-flag" src="assets/landing/flags/' + lang[3] + '" width="20" height="20" alt=""><span>' + lang[1] + '</span>' + (lang[0] === code ? '<span class="lang-state">' + p.active + '</span>' : '');
      button.addEventListener('click', function () { applyLang(lang[0]); document.getElementById('langBtn').focus(); });
      menu.appendChild(button);
    });
  }

  function applyLang(code) {
    if (!P[code]) code = 'uz';
    var p = P[code], meta = languageMeta(code);
    document.documentElement.lang = code;
    document.documentElement.dir = meta[4];
    localStorage.setItem('islamtime_lang', code);
    document.title = 'IslamTimeWorld — ' + p.hero;
    document.querySelector('meta[name="description"]').setAttribute('content', p.sub);
    nth('.nav-link', [p.home,p.features,p.about,p.trust,p.help]);
    text('.skip-link', SKIP[code]); text('.brand-tagline', SLOGANS[code]); text('.hero-signature', SLOGANS[code]);
    label('.btn-download-top', p.openBot); label('.btn-telegram-outline', p.openBot); label('.btn-telegram', p.openBot);
    text('.pill-badge', p.pill); text('.hero-title', p.hero); text('.hero-subtitle', p.sub);
    nth('.feature-chips .chip', [p.langs,p.schools,p.sources]); text('.phones-caption', p.caption);
    nth('.stat-number', [p.sources,p.langs,p.schools,p.updates]); nth('.stat-desc', [p.sourceDesc,p.world,p.schoolDesc,p.quality]);
    text('.section-title', p.featureHead); text('.section-subtitle', p.featureSub);
    nth('.feature-card-title', FEATURE_TITLES[code]);
    if (code !== 'uz') text('.feature-card-desc', p.featureInfo);
    var descriptions = all('.feature-card-desc'); if (descriptions[10]) descriptions[10].textContent = p.liveShort;
    text('.haramayn-title', p.liveTitle); text('.haramayn-text', p.liveText);
    text('[data-live="makkah"]', p.makkah); text('[data-live="madinah"]', p.madinah);
    nth('.box-title', [p.langs,p.schools]); nth('.box-subtitle', [p.oneApp,p.allMuslims]);
    nth('.flag-name', LANGS.map(function (lang) { return lang[1]; }));
    nth('.mazhab-name', p.schoolDesc.split(/[,،]\s*/));
    text('.soon-chip', SOON[code]); label('.btn-video', VIDEO[code]);
    text('.dl-title', p.useToday); text('.dl-subtitle', p.useSub); text('.qr-text', p.scan);
    nth('.footer-links a', [p.privacy,p.terms,p.help,p.contact]);
    var copy = document.querySelector('.footer-copy'); if (copy && copy.firstChild) copy.firstChild.nodeValue = '© 2026 IslamTimeWorld. ' + p.rights + ' ';
    text('.photo-credit', p.photos); var founder = document.querySelector('.footer-founder'); if (founder) founder.innerHTML = 'IslamTimeWorld · ' + p.founder + ': <strong>Mumin Kuziev</strong>';
    var btn = document.getElementById('langBtn'); btn.querySelector('img').src = 'assets/landing/flags/' + meta[3]; btn.querySelector('span').textContent = meta[2]; btn.setAttribute('aria-label', p.choose + ': ' + meta[1]);
    var toggle = document.getElementById('navToggle'); toggle.setAttribute('aria-label', p.menuOpen);
    window.landingMenuLabel = function (open) { return open ? p.menuClose : p.menuOpen; };
    renderMenu(code, p); document.getElementById('langMenu').hidden = true; btn.setAttribute('aria-expanded','false');
  }

  var query = new URLSearchParams(location.search).get('lang');
  var saved = localStorage.getItem('islamtime_lang');
  var browser = (navigator.language || '').toLowerCase().split('-')[0];
  var initial = P[query] ? query : (P[saved] ? saved : (P[browser] ? browser : 'uz'));
  applyLang(initial);
  window.LandingI18n = { apply: applyLang, languages: LANGS };
})();
